AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wetter-bericht

  Sample SAM Template for wetter-bericht

#####################################
# Parameters
#####################################
Parameters:
  StackName:
    Type: String
    Default: wetter-bericht
    Description: The stack name to group this deployment
  DynamoTableName:
    Type: String
    Default: WetterBerichtSubs
    Description: The name of the DynamoDB table

#####################################
# Globals
#####################################
Globals:
  Function:
    Runtime: python3.14
    Timeout: 60
    MemorySize: 512
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        STACK_NAME: !Ref StackName
        DYNAMO_TABLE_NAME: !Ref DynamoTableName
        WEATHER_FANOUT_TOPIC: !Ref WeatherFanoutTopic

#####################################
# Resources
#####################################
Resources:
  # DynamoDB Table
  WeatherSubscriptionsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # SNS Topic - Fanout for weather updates
  WeatherFanoutTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${StackName}-weather-fanout"
  
  # Lambda Function - Weather Dispatcher
  WeatherDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: weather_dispatcher/
      Handler: app.lambda_handler
      Description: 'Wetter Bericht - Dispatcher: fans out daily jobs per subscriber'
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoTableName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref WeatherFanoutTopic

  # Lambda Function - Send Weather Forecast
  SendForecastFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: send_forecast/
      Handler: app.lambda_handler
      Description: 'Wetter Bericht - Send daily weather forecast to subscribed users'
      Events:
        WeatherFanout:
          Type: SNS
          Properties:
            Topic: !Ref WeatherFanoutTopic
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoTableName
        - Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                  - ses:SendRawEmail
                Resource:
                  - "*"

  # Lambda Function - Manage Subscriptions
  ManageSubscriptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: manage_subscriptions/
      Handler: app.lambda_handler
      Description: 'Wetter Bericht - Handles inbound email commands'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoTableName
        - SESCrudPolicy:
            IdentityName: "*"
        - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - ses:SendEmail
              - ses:SendRawEmail
            Resource:
              - arn:aws:s3:::wetter-bericht/*
              - "*"

  # EventBridge Schedule
  DailyForecastSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${StackName}-daily-forecast"
      Description: "Trigger daily weather forecast @ 5 AM EST"
      ScheduleExpression: cron(0 10 * * ? *) # 10 AM UTC / 5 AM EST
      State: ENABLED
      Targets:
        - Arn: !GetAtt WeatherDispatcherFunction.Arn
          Id: WeatherDispatcherTarget

  # Permissions
  WeatherWorkerSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref WeatherFanoutTopic
      Protocol: lambda
      Endpoint: !GetAtt SendForecastFunction.Arn

  PermissionForSNSToInvokeSendForecast:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SendForecastFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref WeatherFanoutTopic

  PermissionForEventBridgeToInvokeDispatcher:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WeatherDispatcherFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyForecastSchedule.Arn


#####################################
# Outputs
#####################################
Outputs:
  WeatherSubscriptionsTable:
    Description: DynamoDB table for storing weather subscriptions
    Value: !Ref DynamoTableName

  SendForecastFunction:
    Description: Send Forecast Lambda Function ARN
    Value: !GetAtt SendForecastFunction.Arn
  
  WeatherDispatcherFunction:
    Description: Weather Dispatcher Lambda Function ARN
    Value: !GetAtt WeatherDispatcherFunction.Arn
    
  WeatherFanoutTopic:
    Description: SNS topic used to fan out weather jobs
    Value: !Ref WeatherFanoutTopic